### ISSUE TITLE
Can you please open source the code for your compiled DLL's for Adiirc? Thanks!

### ISSUE THREAD

**Issue by roboirc** [krystinalynn/AdiIRC-Plugins#2]
Would be good experience for others to learn on how it was done :)
Thanks!

**Comment by krystinalynn** [comment]
I'll open-source this within the next few weeks.

**Comment by roboirc** [comment]
@krystinalynn When will you open source this krystinalynn ? :)

**Comment by krystinalynn** [comment]
> @krystinalynn When will you open source this krystinalynn ? :)

It's now open-sourced, robo! :) 
Source is available [here](https://github.com/krystinalynn/AdiIRC-DJ_Console)
